"""empty message

Revision ID: 930f0f5dedd7
Revises: d90083a93171
Create Date: 2020-11-18 05:33:13.703308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '930f0f5dedd7'
down_revision = 'd90083a93171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('posts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('author_id', table_name='posts')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.create_index('author_id', 'posts', ['user_id'], unique=False)
    op.alter_column('posts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
