FROM python:latest

WORKDIR /var/www

RUN pip install Flask
RUN pip install -U Flask-SQLAlchemy
RUN pip install Flask-Migrate
RUN pip install Flask-Script
RUN pip3 install PyMySQL
RUN pip install cryptography
RUN pip install flask-debugtoolbar
